#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
#tar -zcvf ~/image.tar.gz --directory=/home/user/images/ image.qcow2
SECONDS=0
LC_ALL=C
IFS=" "
cssh="ssh -4 -C -q -o StrictHostKeyChecking=no -o ConnectTimeout=3"

function clean_1() {
	rm -f /run/$(basename $0).pid
}

echo "$BASHPID" > /run/$(basename $0).pid
trap "clean_1; exit" 0 1 2 3 9 15

if ! [[ -f /app/servers.env ]]; then
	echo "ERROR: el archivo /app/servers.env no existe, favor consulte la documentacion."
	exit 1
fi

if ! [[ -f /app/image.tar.gz ]]; then
	echo "ERROR: el archivo /app/image.tar.gz no existe, favor consulte la documentacion."
	exit 1
else
	mv -f /app/image.tar.gz /var/www/html/
fi

while read -r ip puerto usuario password vmid nombre url; do
	echo "$ip", "$puerto", "$usuario", "$password", "$vmid", "$nombre", "$url"
	if [[ "$puerto" == "22" ]]; then
		sshpass -p $password $cssh $usuario@$ip "qm create $vmid --name $nombre --memory 4096 --numa 0 --net0 virtio,bridge=vmbr0,firewall=0,queues=8 --cores 4 --sockets 1 --cpu cputype=host --kvm 1 --acpi 1 --agent 1 --balloon 0 --bios seabios --machine type=q35 --ostype l26 --serial0 socket --hotplug disk,network,usb,memory,cpu --vga qxl --virtio0 local:200,aio=threads,backup=1,format=qcow2,cache=none,iothread=1,media=disk --rng0 source=/dev/urandom --onboot 1 --tablet 0 --watchdog model=i6300esb,action=reset"
		sshpass -p $password $cssh $usuario@$ip "rm -f /var/lib/vz/images/$vmid/vm-$vmid-disk-0.qcow2"
		sshpass -p $password $cssh $usuario@$ip "wget -q $url/image.tar.gz -O /root/image.tar.gz"
		sshpass -p $password $cssh $usuario@$ip "tar -xzf /root/image.tar.gz -C /var/lib/vz/images/$vmid/"
		sshpass -p $password $cssh $usuario@$ip "mv -f /var/lib/vz/images/$vmid/image.qcow2 /var/lib/vz/images/$vmid/vm-$vmid-disk-0.qcow2"
	else
		sshpass -p $password $cssh -p $puerto $usuario@$ip "qm create $vmid --name $nombre --memory 4096 --numa 0 --net0 virtio,bridge=vmbr0,firewall=0,queues=8 --cores 4 --sockets 1 --cpu cputype=host --kvm 1 --acpi 1 --agent 1 --balloon 0 --bios seabios --machine type=q35 --ostype l26 --serial0 socket --hotplug disk,network,usb,memory,cpu --vga qxl --virtio0 local:200,aio=threads,backup=1,format=qcow2,cache=none,iothread=1,media=disk --rng0 source=/dev/urandom --onboot 1 --tablet 0 --watchdog model=i6300esb,action=reset"
		sshpass -p $password $cssh $usuario@$ip "rm -f /var/lib/vz/images/$vmid/vm-$vmid-disk-0.qcow2"
		sshpass -p $password $cssh -p $puerto $usuario@$ip "wget -q $url/image.tar.gz -O /root/image.tar.gz"
		sshpass -p $password $cssh -p $puerto $usuario@$ip "tar -xzf /root/image.tar.gz -C /var/lib/vz/images/$vmid/"
		sshpass -p $password $cssh -p $puerto $usuario@$ip "mv -f /var/lib/vz/images/$vmid/image.qcow2 /var/lib/vz/images/$vmid/vm-$vmid-disk-0.qcow2"
	fi
	echo "==================="
done < ./servers.env

echo "duracion $SECONDS segundos"
echo "Finalizado."
exit 0
