#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
SECONDS=0
LC_ALL=C
IFS=" "
LOCKFILE="/tmp/$(basename $0)_$(whoami)"
LOCKFD="150"
cssh="ssh -4 -C -q -o StrictHostKeyChecking=no -o ConnectTimeout=3"
fecha=$(date +%d-%m-%Y)

function lock () {
	echo {LOCKFD}>$LOCKFILE
	flock -n $LOCKFD
}

function exit_error () {
	echo "ERROR: Ya hay una instancia en ejecución. Saliendo"
	exit 1
}

function clean_1() {
	rm -f /tmp/$(basename $0)_$(whoami)
	rm -f /run/$(basename $0).pid
}

echo "$BASHPID" > /run/$(basename $0).pid
trap "clean_1; exit" 0 1 2 3 9 15
lock || exit_error

if ! [[ -f /app/servers.env ]]; then
	echo "ERROR: el archivo /app/servers.env no existe, favor consulte la documentacion."
	exit 1
fi

if ! [[ -f /app/image.tar.gz ]]; then
	echo "ERROR: el archivo /app/image.tar.gz no existe, favor consulte la documentacion."
	exit 1
else
	mv -f /app/image.tar.gz /var/www/html/
fi

while read -r ip puerto usuario clave password vmid nombre url; do
	echo "$ip", "$puerto", "$usuario", "$password", "$vmid", "$nombre", "$url"
	if [[ "$puerto" == "22" ]]; then
		sshpass -p $password $cssh $usuario@$ip "qm create $vmid --name $nombre --memory 4096 --numa 0 --net0 virtio,bridge=vmbr0,firewall=0,queues=8 --cores 4 --sockets 1 --cpu cputype=host --kvm 1 --acpi 1 --agent 1 --balloon 0 --bios seabios --machine type=q35 --ostype l26 --serial0 socket --hotplug disk,network,usb,memory,cpu --vga qxl --virtio0 local:200,aio=threads,backup=1,format=qcow2,cache=none,iothread=1,media=disk --rng0 source=/dev/urandom --onboot 1 --tablet 0 --watchdog model=i6300esb,action=reset"
	else
		sshpass -p $password $cssh -p $puerto $usuario@$ip "qm create $vmid --name $nombre --memory 4096 --numa 0 --net0 virtio,bridge=vmbr0,firewall=0,queues=8 --cores 4 --sockets 1 --cpu cputype=host --kvm 1 --acpi 1 --agent 1 --balloon 0 --bios seabios --machine type=q35 --ostype l26 --serial0 socket --hotplug disk,network,usb,memory,cpu --vga qxl --virtio0 local:200,aio=threads,backup=1,format=qcow2,cache=none,iothread=1,media=disk --rng0 source=/dev/urandom --onboot 1 --tablet 0 --watchdog model=i6300esb,action=reset"
		#descargar imagen y colocarla en el directorio correcto
	fi
	echo "==================="
done < ./servers.env

echo "duracion $SECONDS segundos"
echo "Finalizado."
exit 0
